### ISSUE TITLE
read() method bombs when page DOM size exceeds 8k

### ISSUE THREAD

**Issue by garris** [weisjohn/sleepyhollow-node#1]
This is the error I am getting on the console...

```
Wed, 16 Jul 2014 19:47:50 GMT uncaughtException SyntaxError: Unexpected end of input
Error: SyntaxError: Unexpected end of input
    at read (/Users/gshipon/Sites/judy2/node_modules/sleepyhollow-node/index.js:43:19)
    at Array.forEach (native)
    at Socket.<anonymous> (/Users/gshipon/Sites/judy2/node_modules/sleepyhollow-node/index.js:20:37)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
logout
```

and this is the method...

```
    // the read mechanism that selectively writes
    function read(data) {
        if (!data) return;
        try { data = JSON.parse(data) }
        catch (e) { 
            console.log(e, data); 
            throw new Error(e); 
        }
        _emit.apply(sleepyhollow, [data.event, data.message]);
        if (data.event == "ack") return;
        write({ "event": "ack" });
        _write();
    }
```

Maybe some kind of deliberate chunking going on?  Would like to see if I could pass a 100k DOM through here.  Any advice?

**Comment by weisjohn** [comment]
When I was coming up with this solution, I had a "shower-thought" and wrote it down really quickly before I implemented it. Here's that artifact: ![](http://i.johnweis.com/phantom_to_node.jpg?v=1)

This bug is probably a limitation in with PhantomJS's write line buffer. Basically, this module along with sleepyhollow-phantom, implements a co-ordinated write read mechanism, and it assume that everything that is coming across `stderr` will be a full JSON package.

Alternatively, it could be a problem with the data coming across. If there's something that's tripping the readline, then we'd need to look at the escaping.

Could you post the essential portions of the node and phantom scripts, along with the data that you're trying to pass over?

**Comment by garris** [comment]
Thanks for the explanation.   Very nice.  

It's probably not the data, I initially had the issue rendering production code and was then able to recreate the issue again with this test file... https://gist.github.com/garris/5d03f2f8411afc76f75d

You should see the problem with this file -- remove the last 1k chunk and you will see the problem go away.

And yes, I can see this guy wouldn't like an incomplete packet... `try { data = JSON.parse(data) }`

I'm putting together code samples to demonstrate the implementation.  Will post that soon...

**Comment by garris** [comment]
ok,  here is the implementation.  As I said, this all works great when the event data I'm passing out of phantom is under 8k.  Over that amount and somewhere along the line it's truncated.

in the script which is run by PhantomJS...

```
    page.open(url, function(status) {
            //page is loaded

            var c = page.content; //lets say this is the contents of the html gist above

            console.log(c); // if over 8k this will get truncated

            mrhyde.emit("loaded",c);  //   &/or this will get truncated too

    });
```

node side script... When under 8k this is called successfully.  The above script bombs when PhantomJS page content is above 8k -- so this one doesn't get called.

```
        //called after a successful load
        drjekyll.on('loaded', function(phantomOut) {
            res.send(phantomOut);
        });
```

**Comment by weisjohn** [comment]
Ok, so if PhantomJS is truncating the 8k `console.log` statement, then that means it's PhantomJS's "fault". That being said, I can think of a work-around, which will require changes to both this module and the sister module. First, in `sleepyhollow-phantom`, we need to see if the message is longer than 8k. If it is, we need to break it up and send multiple calls. On the `sleepyhollow-node` side, we need to attempt to parse, and if it fails, wait til the next call, append and then reparse.

Does that make sense?  Do you want to try to tackle this?

**Comment by garris** [comment]
Yes,  this is where I was going with it.   But I was thinking,  continually retrying is probably not necessary.  I think we can measure the string prior to putting it on the bus.  Why not extend your transport with a randomly generated 'multipart ID'.  The receiving end can hash this and build a respective data string until say an EOF signal with a matching multipart ID is received.  Then evaluate.  Not unlike email.

That said, is there an existing bug already for this on the phantom project?   The average DOM is supposed to be something like 50k so a bug like this shouldn't go un noticed...

What do you think?

---

**Comment by weisjohn** [comment]
That would be a good way to approach it. 

There isn't an existing issue filed, but it definitely is a bug. I don't have a need to pass through whole web pages, so I haven't yet run into the bug before.  Usually, I'll do some parsing / rendering work on the phantomjs side, and then simply pass a notification back over to mark something done on the queue. So, yeah, this is a bug, but I haven't seen it before.

**Comment by garris** [comment]
Ok,  it's now working with the test data.  I think this is a good fix.  I created a pull request.   I hope I didn't miss anything important -- let me know what you think.  I will do some stress testing next week when I implement my SEO project.

BTW: I don't think the stdio chunking is a bug.  Popular opinion here is that it is working as designed and it's setting is probably optimal given the primary use case.  In any case, this fix will be completely transparent to end users and reliably pass messages of _any size_ over the bus.

**Comment by garris** [comment]
Hey John,  Just checking in.   Since the fix I have been using sleepyhollow without error.    I noticed you haven’t done the merge.  Just wondering if you had any feedback for me.   Best, Garris

**Comment by weisjohn** [comment]
@garris sorry, I was on vacation. I'll take a look tonight.

**Comment by garris** [comment]
Sure — no worries and no rush.   Best,  Garris

**Comment by weisjohn** [comment]
@garris I know that is super old, but I was wondering if you could tell me what version of phantom you were using?

**Comment by garris** [comment]
Totally don't remember.  Sorry.   FWIW: it's likely I was using whatever the production version was at the time.

**Comment by weisjohn** [comment]
@garris awesome! Thanks so much for a speedy reply!  I found some time to clean this up again and will release something soon.
